// Generated by scripts/generate_orbit_menu.py; do not edit.
#pragma once
#include <cstdint>
namespace OrbitMenu {
constexpr int kPageSize = 466;
// One menu page: 256 RGB565 colours and one palette index per pixel,
// row by row, kPageSize x kPageSize.
struct Page {
    const uint16_t* palette;
    const uint8_t* pixels;
};
// Indexed by menu page: 0 List, 1 Timers, 2 Notes.
extern const Page kPages[3];
}  // namespace OrbitMenu
