// Generated by scripts/generate_orbit_menu.py; do not edit.
#pragma once
#include "lvgl.h"
namespace OrbitMenu {
// Where a mark sits on the 466 px menu panel (top-left corner).
struct Mark {
    const lv_image_dsc_t* image;
    int x;
    int y;
};
extern const lv_image_dsc_t kListImage;
extern const lv_image_dsc_t kTimersImage;
extern const lv_image_dsc_t kNotesImage;
extern const lv_image_dsc_t kDotOnImage;
extern const lv_image_dsc_t kDotOffImage;
// Indexed by menu page: 0 List, 1 Timers, 2 Notes.
extern const Mark kMarks[3];
constexpr int kDotSize = 12;
constexpr int kDotTop = 345;
constexpr int kDotLeft(int index) {
    return 227 + (index - 1) * 16;
}
}  // namespace OrbitMenu
