#!/usr/bin/env python3
"""Pack the menu drawing (menu_art/page-*.png) into flash-sized page images.

Drawing G4a fills the whole round screen: one 466 x 466 frame per page,
rendered from menu_art/orbit-menu-g4a.html (#export=<page>). Three frames
in RGB565 would not fit in ota_0, so each page is stored as 256 colours:
a palette of RGB565 values and one index byte per pixel, Floyd-Steinberg
dithered by Pillow. The firmware expands the page it shows into a single
RGB565 buffer in PSRAM (RoundLcdDisplay::PaintMenuPageLocked).

    python3 scripts/generate_orbit_menu.py [--preview OUT_DIR]

--preview decodes the packed pages back to PNG, exactly as the ring expands
them, and prints how far each is from its master.
"""

import argparse
import math
from pathlib import Path

from PIL import Image


BOARD = Path(__file__).resolve().parents[1] / "main/boards/m5stack/stopwatch"
ART = BOARD / "menu_art"
SCREEN = 466
# Menu pages in swipe order; the index is the page ShowOrbitMenu receives.
PAGES = ("list", "timers", "notes")


def master(name):
    image = Image.open(ART / f"page-{name}.png").convert("RGB")
    assert image.size == (SCREEN, SCREEN), f"page-{name}.png must be {SCREEN} px square"
    return image


def rgb565(r, g, b):
    return (round(r * 31 / 255) << 11) | (round(g * 63 / 255) << 5) | round(b * 31 / 255)


def pack(image):
    """(palette of 256 RGB565 values, index bytes) for one page."""
    indexed = image.quantize(colors=256, method=Image.Quantize.MEDIANCUT,
                             dither=Image.Dither.FLOYDSTEINBERG)
    flat = indexed.getpalette()[:256 * 3]
    flat += [0] * (256 * 3 - len(flat))
    palette = [rgb565(*flat[i:i + 3]) for i in range(0, 256 * 3, 3)]
    assert 0 in palette, "pure black must survive: the screen edge and glass are black"
    return palette, indexed.tobytes()


def expand(palette, pixels):
    image = Image.new("RGB", (SCREEN, SCREEN))
    rgb = []
    for index in pixels:
        value = palette[index]
        rgb.append(((value >> 11) * 255 // 31, ((value >> 5) & 0x3F) * 255 // 63,
                    (value & 0x1F) * 255 // 31))
    image.putdata(rgb)
    return image


def identifier(name):
    return name.capitalize()


def generate():
    header = ["// Generated by scripts/generate_orbit_menu.py; do not edit.",
              "#pragma once", "#include <cstdint>", "namespace OrbitMenu {",
              f"constexpr int kPageSize = {SCREEN};",
              "// One menu page: 256 RGB565 colours and one palette index per pixel,",
              "// row by row, kPageSize x kPageSize.",
              "struct Page {", "    const uint16_t* palette;", "    const uint8_t* pixels;", "};",
              "// Indexed by menu page: 0 List, 1 Timers, 2 Notes.",
              "extern const Page kPages[3];", "}  // namespace OrbitMenu"]
    source = ["// Generated by scripts/generate_orbit_menu.py; do not edit.",
              '#include "sdkconfig.h"', "#if CONFIG_PROVISIONS_GATEWAY_REQUIRED",
              '#include "menu_asset.h"', "namespace OrbitMenu {"]
    total = 0
    for name in PAGES:
        key = identifier(name)
        palette, pixels = pack(master(name))
        total += len(pixels) + 2 * len(palette)
        source.append(f"alignas(4) static const uint16_t k{key}Palette[256] = {{")
        source.extend("    " + ",".join(f"0x{v:04x}" for v in palette[i:i + 16]) + ","
                      for i in range(0, 256, 16))
        source.extend(["};", f"alignas(4) static const uint8_t k{key}Pixels[{len(pixels)}] = {{"])
        source.extend("    " + ",".join(f"0x{b:02x}" for b in pixels[i:i + 32]) + ","
                      for i in range(0, len(pixels), 32))
        source.append("};")
    source.append("const Page kPages[3] = {")
    source.extend(f"    {{k{identifier(name)}Palette, k{identifier(name)}Pixels}}," for name in PAGES)
    source.extend(["};", "}  // namespace OrbitMenu", "#endif"])
    (BOARD / "menu_asset.h").write_text("\n".join(header) + "\n")
    (BOARD / "menu_asset.cc").write_text("\n".join(source) + "\n")
    print(f"Packed {len(PAGES)} menu pages, {total:,} bytes.")


def preview(out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in PAGES:
        source = master(name)
        shown = expand(*pack(source))
        shown.save(out_dir / f"menu-{name}.png")
        error = sum((a - b) ** 2 for p, q in zip(source.getdata(), shown.getdata())
                    for a, b in zip(p, q)) / (SCREEN * SCREEN * 3)
        psnr = 10 * math.log10(255 ** 2 / error) if error else float("inf")
        print(f"{name}: {psnr:.1f} dB against the master")
    print(f"Wrote {len(PAGES)} preview pages to {out_dir}.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", metavar="OUT_DIR")
    args = parser.parse_args()
    if args.preview:
        preview(args.preview)
    else:
        generate()
