#!/usr/bin/env python3
"""Render the immutable crest into two cropped LVGL A8 masks (CairoSVG/Pillow).

This is deterministic asset conversion, not artwork editing. The source hash,
contours, viewBox, transform and fill rule are retained and verified.
"""

import hashlib
import io
from pathlib import Path
import re
import xml.etree.ElementTree as ET

import cairosvg
from PIL import Image, ImageChops, ImageDraw


BOARD = Path(__file__).resolve().parents[1] / "main/boards/m5stack/stopwatch"
SOURCE_HASH = "92c8326411d6b07a87b9b18aadb6cd1f137886e2ec88b553970f2e9bd8bb20bd"
SIZE = 384


def masks():
    # The checked-in text copy has a terminal newline; the supplied file did
    # not. Hash its otherwise byte-identical payload, without changing either.
    original = (BOARD / "provisionscrestexact.svg").read_bytes().removesuffix(b"\n")
    assert hashlib.sha256(original).hexdigest() == SOURCE_HASH
    root = ET.fromstring(original)
    paths = root.findall(".//{http://www.w3.org/2000/svg}path")
    assert len(paths) == 1
    path = paths[0]
    data = path.attrib["d"]
    contours = list(re.finditer("[Mm]", data))
    assert len(contours) == 3 and contours[2].group() == "M"

    def render(svg):
        png = cairosvg.svg2png(bytestring=svg, output_width=SIZE, output_height=SIZE)
        return Image.open(io.BytesIO(png)).convert("RGBA").getchannel("A")

    full = render(original)
    # Rasterize the compound path once. Rendering contours separately changes
    # Cairo's edge coverage on 117 pixels (up to 15/255), despite identical
    # geometry. Separate the central connected component from this ONE exact
    # raster instead, retaining each original antialiased alpha byte.
    labels = full.point(lambda alpha: 255 if alpha else 0)
    assert labels.getpixel((SIZE // 2, SIZE // 2)) == 255
    ImageDraw.floodfill(labels, (SIZE // 2, SIZE // 2), 128)
    alpha = full.tobytes()
    membership = labels.tobytes()
    star = Image.frombytes("L", full.size, bytes(a if m == 128 else 0
                                               for a, m in zip(alpha, membership)))
    assert star.getbbox() and 90 < star.getbbox()[2] - star.getbbox()[0] < 120
    band = ImageChops.subtract(full, star)
    layers = [band, star]
    assert ImageChops.lighter(*layers).tobytes() == full.tobytes()
    assert ImageChops.darker(*layers).getbbox() is None
    return layers


def generate():
    header = ["#pragma once", '#include "lvgl.h"', "namespace OrbitCrest {"]
    source = ['// Generated by scripts/generate_orbit_crest.py; do not edit.',
              '#include "sdkconfig.h"', '#if CONFIG_PROVISIONS_GATEWAY_REQUIRED',
              '#include "crest_asset.h"', 'namespace OrbitCrest {']
    for name, layer in zip(("Band", "Star"), masks()):
        box = layer.getbbox()
        crop = layer.crop(box)
        data = crop.tobytes()
        header.extend([f"extern const lv_image_dsc_t k{name}Image;",
                       f"constexpr int k{name}X = {41 + box[0]};",
                       f"constexpr int k{name}Y = {41 + box[1]};"])
        source.append(f"alignas(4) static const uint8_t k{name}Alpha[] = {{")
        source.extend("    " + ",".join(f"0x{b:02x}" for b in data[i:i+24]) + ","
                      for i in range(0, len(data), 24))
        source.extend(["};", f"const lv_image_dsc_t k{name}Image = [] {{",
                       "    lv_image_dsc_t image{};",
                       "    image.header.magic = LV_IMAGE_HEADER_MAGIC;",
                       "    image.header.cf = LV_COLOR_FORMAT_A8;",
                       f"    image.header.w = {crop.width};",
                       f"    image.header.h = {crop.height};",
                       f"    image.header.stride = {crop.width};",
                       f"    image.data_size = sizeof(k{name}Alpha);",
                       f"    image.data = k{name}Alpha;",
                       "    return image;", "}();"])
    header.append("}  // namespace OrbitCrest")
    source.extend(["}  // namespace OrbitCrest", "#endif"])
    (BOARD / "crest_asset.h").write_text("\n".join(header) + "\n")
    (BOARD / "crest_asset.cc").write_text("\n".join(source) + "\n")
    print("Exact crest verified; generated two non-overlapping A8 masks.")


if __name__ == "__main__":
    generate()
